# Generated by Django 5.1.5 on 2025-08-15 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('cover_image', models.URLField(blank=True)),
                ('released', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('genres', models.TextField(blank=True)),
                ('styles', models.TextField(blank=True)),
                ('labels', models.TextField(blank=True)),
                ('formats', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tracklist_JSON', models.JSONField(blank=True, default=list)),
                ('tags', models.ManyToManyField(blank=True, related_name='records', to='collection.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('preview_url', models.URLField(blank=True)),
                ('deezer_link', models.URLField(blank=True)),
                ('deezer_artists', models.TextField(blank=True)),
                ('deezer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='collection.userrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RecordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='list_covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('records', models.ManyToManyField(related_name='lists', to='collection.userrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_record', to=settings.AUTH_USER_MODEL)),
                ('record_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collection.userrecord')),
                ('record_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collection.userrecord')),
                ('record_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collection.userrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discogs_master_id', models.CharField(blank=True, max_length=255, null=True)),
                ('discogs_release_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'discogs_master_id', 'discogs_release_id')},
            },
        ),
    ]
