# Generated by Django 5.1.5 on 2025-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='formats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='genres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='labels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='released',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='styles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
