# Generated by Django 5.1.5 on 2025-08-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_cachedmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.CharField(max_length=50, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
