# Generated by Django 5.1.5 on 2025-06-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_userrecord_avg_rating_userrecord_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='avg_rating',
        ),
    ]
