# Generated by Django 5.1.5 on 2025-06-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_userrecord_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('preview_url', models.URLField(blank=True)),
                ('deezer_link', models.URLField(blank=True)),
                ('deezer_artists', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracklist', to='collection.userrecord')),
            ],
        ),
    ]
