# Generated by Django 5.1.5 on 2025-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='tracklist_JSON',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
