# Generated by Django 5.1.5 on 2025-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_excludedrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='artists',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='artists',
            field=models.ManyToManyField(related_name='records', to='collection.artist'),
        ),
    ]
