# Generated by Django 5.1.5 on 2025-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_artist_remove_userrecord_artists_userrecord_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='discogs_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
