# Generated by Django 5.1.5 on 2025-06-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_userrecord_tracklist_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='collection.userrecord'),
        ),
    ]
