# Generated by Django 5.1.5 on 2025-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_recordlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
