# Generated by Django 5.1.5 on 2025-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_track_deezer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='deezer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
