# Generated by Django 5.1.5 on 2025-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_recordlist_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='list_covers/'),
        ),
    ]
