# Generated by Django 5.1.5 on 2025-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_alter_recordlist_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
