# Generated by Django 5.1.5 on 2025-01-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('records', models.ManyToManyField(related_name='collections', to='records.record')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='users.user')),
            ],
        ),
    ]
