# Generated by Django 5.1.5 on 2025-09-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
