# Generated by Django 5.1.5 on 2025-09-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_collection'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='records',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='records',
        ),
        migrations.RemoveField(
            model_name='image',
            name='record',
        ),
        migrations.RemoveField(
            model_name='label',
            name='records',
        ),
        migrations.RemoveField(
            model_name='style',
            name='records',
        ),
        migrations.RemoveField(
            model_name='track',
            name='record',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
